server:
  port: 3001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db-firebody

logging:
  level:
    ru.icqparty.firebody.server: DEBUG
    org.mongodb: ERROR
    org.springframework: ERROR
  file: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"