server:
  port: 3001

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
   url: jdbc:mysql://localhost:3306/db_example
   username: springuser
   password: ThePassword

logging:
  level:
    ru.icqparty.firebody.server: DEBUG
    org.mongodb: ERROR
    org.springframework: ERROR
  file: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"